In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [68]:
import glob
import string, os
import numpy as np
import pandas as pd 
import keras.utils as ku
from numpy.random import seed
from keras.models import Sequential
from tensorflow import set_random_seed
from keras.callbacks import EarlyStopping
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Embedding, LSTM, Dense, Dropout

In [3]:
data = """The cat and her kittens
They put on their mittens,
To eat a Christmas pie.
The poor little kittens
They lost their mittens,
And then they began to cry.
O mother dear, we sadly fear
We cannot go to-day,
For we have lost our mittens."
"If it be so, ye shall not go,
For ye are naughty kittens."""

In [ ]:
tokenizer = Tokenizer()

In [1]:
def dataset_preparation(data):
    corpus = data.lower().split("\n")
    tokenizer.fit_on_texts(corpus)
    total_words = len(tokenizer.word_index) + 1 
    input_sequences = []
    for line in corpus:
#         print(line)
        token_list = tokenizer.texts_to_sequences([line])[0]
#         print(token_list)
        for i in range(1, len(token_list)):
            n_gram_sequence = token_list[:i+1]
#             print("Ngram",n_gram_sequence)
            input_sequences.append(n_gram_sequence)
#     print("Input_Sequence",input_sequences)
    max_sequence_len = max([len(x) for x in input_sequences])
#     print(max_sequence_len)
    input_sequences = np.array(pad_sequences(input_sequences,   
                          maxlen=max_sequence_len, padding='pre'))
#     print(input_sequences)
#     print("\n")
#     print("\n")
    predictors, label = input_sequences[:,:-1],input_sequences[:,-1]
#     print("Predictors",predictors)
#     print("Labels",label)
    label = ku.to_categorical(label, num_classes=total_words)
#     print("Transformed_Labels",label)
    return predictors,label,max_sequence_len,total_words

def create_model(predictors, label, max_sequence_len, total_words):
    input_len = max_sequence_len - 1

    model = Sequential()
    model.add(Embedding(total_words, 10, input_length=input_len))
    model.add(LSTM(150))
    model.add(Dropout(0.1))
    model.add(Dense(total_words, activation='softmax'))

    model.compile(loss='categorical_crossentropy', optimizer='adam')
    model.fit(predictors, label, epochs=100, verbose=1)
    return model

def generate_text(seed_text, next_words, max_sequence_len, model):
    for j in range(next_words):
        print(j)
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        print(token_list)
        token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
        print(token_list)
        predicted = model.predict_classes(token_list, verbose=0)
        print(predicted)
  
        output_word = ""
        for word, index in tokenizer.word_index.items():
            if index == predicted:
                output_word = word
                print("Word",word)
                print("Index",index)
                break
        seed_text += " " + output_word
    return seed_text

In [106]:
text = generate_text("we naughty", 3, max_len, model)

0
[5, 42]
[[ 0  0  0  0  0  5 42]]
[10]
Word go
Index 10
1
[5, 42, 10]
[[ 0  0  0  0  5 42 10]]
[4]
Word to
Index 4
2
[5, 42, 10, 4]
[[ 0  0  0  5 42 10  4]]
[3]
Word mittens
Index 3


In [107]:
print(text)

we naughty go to mittens


In [88]:
X, Y, max_len, total_words = dataset_preparation(data)

In [96]:
model = create_model(X, Y, max_len, total_words)

Epoch 1/100
48/48 [==============================] - 2s 35ms/step - loss: 3.7621
Epoch 2/100
48/48 [==============================] - 0s 977us/step - loss: 3.7593
Epoch 3/100
48/48 [==============================] - 0s 326us/step - loss: 3.7564
Epoch 4/100
48/48 [==============================] - 0s 326us/step - loss: 3.7535
Epoch 5/100
48/48 [==============================] - 0s 325us/step - loss: 3.7512
Epoch 6/100
48/48 [==============================] - 0s 977us/step - loss: 3.7467
Epoch 7/100
48/48 [==============================] - 0s 651us/step - loss: 3.7446
Epoch 8/100
48/48 [==============================] - 0s 651us/step - loss: 3.7384
Epoch 9/100
48/48 [==============================] - 0s 651us/step - loss: 3.7337
Epoch 10/100
48/48 [==============================] - 0s 651us/step - loss: 3.7262
Epoch 11/100
48/48 [==============================] - 0s 326us/step - loss: 3.7162
Epoch 12/100
48/48 [==============================] - 0s 651us/step - loss: 3.7075
Epoch 13/100
4

In [97]:
model

In [ ]:
genera